### ISSUE TITLE
stATOM display bug

### ISSUE THREAD

**Issue by asalzmann** [osmosis-labs/osmosis-frontend#1046]
The default coins for the swap feature are ATOM / OSMO. For some reason, when ATOM is the upper coin in the selector, if you click ATOM and try to change to stATOM, the coin is not found. Sometimes I can find stATOM, most of the time not (I haven't figured out the pattern yet). It seems like the tokens slowly load into the search modal, and only become selectable once they are loaded.

![Screen Shot 2022-11-22 at 11 08 12 PM](https://user-images.githubusercontent.com/1331345/203609096-9b2ab294-0627-4890-8143-73d0aaff8b21.png)

**Comment by JeremyParish69** [comment]
I think I've found the pattern. The asset selector intentionally omits the asset already selected. My guess is that when ATOM is selected, it also mistakenly filters out stATOM since that denom also contains 'atom''. This is repeatable when the selected asset is OSMO and you try to change it to stOSMO. Interestingly, when one selector has ATOM, the other selector correctly filters out ATOM, but does not filter out stATOM, so the filtering mechanism seems slightly different for each.
