### ISSUE TITLE
New user: show fee details in IBC transfer dialog

### ISSUE THREAD

**Issue by jonator** [osmosis-labs/osmosis-frontend#413]
It may not be obvious to a user that the "Available balance", if sent exactly, would actually fail because none was set aside for fees (the "max" button accounts for this). We should display this concept in the UI somehow.

**Comment by jonator** [comment]
6/28 sprint planning. -


Background:

![Image](https://user-images.githubusercontent.com/4606373/176248300-c8770634-a73f-4e40-813b-c079eb87a0f6.png)

Just when depositing IBC. Should add UI next to available showing swap fee amount to reduce confusion on amount difference.

**Comment by victortokaito** [comment]
"Gas fees" correct @jonator? Should I mention that this is due to the originating chain so users know it's not an Osmosis fee?

**Comment by victortokaito** [comment]
Longer term, we want it to feel like users can easily interact with assets no matter the chain.
Yeah, it’s a small point of UX, but I’d like to emphasize to users that the gas fee is akash’s since osmosis’ gas is variable.

Related issue:  For clarity, I think implementing the user-selected gas fee UI makes sense since we can’t show this as part of the estimate (the osmosis gas fee is only shown after the fact—selection in Keplr). It can be kind of confusing that gas is not included in the transaction summary. #377

**Comment by jonator** [comment]
@victortokaito thinking of closing this issue. I don't think it's that valuable for users - or - not worth the UI complexity.

**Comment by victortokaito** [comment]
<img width="762" alt="Screen Shot 2022-08-24 at 9 53 54 AM" src="https://user-images.githubusercontent.com/39136683/186477500-2d2c3bff-597c-48e4-ae58-a81be08767de.png">

@jonator do you think the new fee detail section adequately addresses this?
