### ISSUE TITLE
Disable "Create New Pool" button

### ISSUE THREAD

**Issue by jonator** [osmosis-labs/osmosis-frontend#414]
Almost one year into Osmosis being live, it's clear that the typical app.osmosis.zone user would/should not really be creating pools. Pools are typically created directly by project teams via the CLI.

**Comment by JeremyParish69** [comment]
Can this perhaps just be hidden as an advanced setting rather than deleted? Many teams creating pools either don't have CLI installed, or are unsure about the parameters to enter using CLI, and therefore request a staging link so they can instead use the UI to create a pool instead--which they could also just use to confirm what the default parameters are (e.g., future governor).

Also, I use it to check if I have any unbonded GAMM.

**Comment by jonator** [comment]
@JeremyParish69 Thanks for the insight, will icebox for now.

**Comment by jonator** [comment]
Leaving because we think the possibility of creating a pool is more permissionless, even if most users aren't using it.
