### ISSUE TITLE
Add stable coin info/disclaimer

### ISSUE THREAD

**Issue by jonator** [osmosis-labs/osmosis-frontend#481]
In light of the current UST situation, we should help our users make the right decision around the use of stable coins. We should add links next to stable coins in the assets page that jump to a docs page explaining the risks associated with each type of stable coin.

This issue tracks various tasks
- [ ] Design - warning in add liquidity dialog @syed8rahman @victortokaito
- [ ] ~~Docs - a page on docs.osmosis.zone providing info about the types of stables (w/ a breakdown of the types of collateralized assets) @daniel-farina (necessary?)~~
- [ ] Development - adding the warning to the refactor development stream @jonator 
- [x] Config - Add a flag in ibc config to indicate that this transferred asset is a stable coin @JeremyParish69

**Comment by JeremyParish69** [comment]
Regarding the Config flag,
-considering possible locations:
--could have under IBCAssetInfos; this seems to be limited to data directly pertaining to depositing or withdrawing IBC assets to/from Osmosis. Information about whether it's a stablecoin doesn't really fit here. If we put it here, it only needs to be specified once.
--could have under EmbedChainInfos; the seems to be mostly limited to data pertaining to Keplr's Sggest Chain feautre. Information about whether it's a stablecoin isn't required for that. However, I think specifying the token logo is also not used for Keplr's Suggest Chain feature, and yet we put the URL in here. It would also beg the question of whether the flag must be repeated wherever the stablecoin is used as a staking currency or fee currency (e.g., UST is used as a Fee currency).

---I'm leaning to put it under EmbedChainInfos, and only under the Currencies section.

-considering what//how to indicate the flag:
--simplest option is something like a boolean-- "isStable": true,
--there is opportunity to include more information about the stablecoin, such as index or mechanism
---e.g., "stableMechanism": "aglorithmic" (or "debt", or "reserve"?)--this opens a lot of questions about how to categorize, and could quickly become outdated due to special blends of mechanisms or now mechanisms
---e.g., "index": "United States Dollar" -- this could apply beyond to non-fiat or synthetics

--currently leaning to keep it simple for now with just "isStable" boolean, although could be worth discussing these other options later.

**Comment by jonator** [comment]
Two points
* `isStable` may be misleading, and may have readers think it refers to the stability of the associated chain. IMO a better alternative would be `pegMechanism`
* For now, all we need is an indicator or for the primary type of stable coin it is. Other info is overkill for now and could be added later. This could be described by the type- `pegMechanism?: "collateralized" | "algorithmic"`. (note the optional member)

**Comment by JeremyParish69** [comment]
> Two points
> 
> * `isStable` may be misleading, and may have readers think it refers to the stability of the associated chain. IMO a better alternative would be `pegMechanism`
> * For now, all we need is an indicator or for the primary type of stable coin it is. Other info is overkill for now and could be added later. This could be described by the type- `pegMechanism?: "collateralized" | "algorithmic"`. (note the optional member)

Good points, but in the case of Fei, where it's first treasury, and then fails over to algorithmic, or in the case of FRAX where it's simultaneously both collateralized and algorithmic, we should probably allow for cases like "hybrid" and maybe even "other"

**Comment by jonator** [comment]
I agree with that. It doesn't account for those hybrid cases, where I think a "hybrid" symbol would work well for.

**Comment by jonator** [comment]
@victortokaito is there a link to design yet?

**Comment by jonator** [comment]
@daniel-farina do you think it's necessary to link to osmosis docs? Or just say that they're risky? I've thought about it more and I think linking to a docs site may be overkill.

**Comment by victortokaito** [comment]
<img width="646" alt="Screen Shot 2022-05-16 at 1 32 53 PM" src="https://user-images.githubusercontent.com/39136683/168677860-1043bb85-0033-4777-a339-e0ed57c8d949.png">
<img width="426" alt="Screen Shot 2022-05-16 at 1 29 55 PM" src="https://user-images.githubusercontent.com/39136683/168677946-25021d99-d341-4d2b-bb42-c7c945a3939a.png">

Good point Jeremy, I was thinking the [same with this](https://www.figma.com/file/UXgL2cPiw5I4GALDOodfCy/Osmosis-Web-(Master-File)?node-id=1559%3A24721). I changed it to hybrid-backed from algo because I'm not sure I see any purely algorithmic stablecoins appearing in the near future. Do you foresee us adding new algo stables any time soon?

**Comment by jonator** [comment]
@victortokaito what if we use the standard info box UI within the box for a selected stable coin token? It may make it more clear which token the error is about.

**Comment by jonator** [comment]
Removing docs tasks. Docs about stables is out of our wheelhouse.

**Comment by jonator** [comment]
Adding to refactor as it is close to completion.

**Comment by victortokaito** [comment]
Yep, I added the standard info box you suggested [here](https://www.figma.com/file/UXgL2cPiw5I4GALDOodfCy/Osmosis-Web-(Master-File)?node-id=1611%3A26579). Original version is below for comparison.
