### ISSUE TITLE
Use Axelar SDK `getTransferFee`

### ISSUE THREAD

**Issue by jonator** [osmosis-labs/osmosis-frontend#982]
### Problem
Currently, transfer fees are hardcoded with each asset in the Axelar source chain config file. When I initially built the integration, I tried to utilize the `getTransferFee` query from the Axelar SDK, but ran into issues. This means whenever the fee changes for any network<>asset combo, we need to manually update the config (like on Nov 10).

https://github.com/osmosis-labs/osmosis-frontend/blob/0fddb0647993d5effc32fca8b84f9917a998e2fb/packages/web/integrations/axelar/source-chain-config.ts#L20

### Proposed Solution
Perhaps upgrade the AxelarJS SDK, and see if we can get the `getTransferFee` query to work. Reach out to Canh Trinh from Axelar with any issues.

**Comment by JeremyParish69** [comment]
This is really exciting! In the interest of reducing the manual effort (of adding an Axelar asset or withdraw network) even further, would it be difficult to do the same for the erc20 addresses as well( after this)? If so, we'd probably be able to get rid of the source-chain-config.ts file completely, since (network) "id" and "logoUrl" could be moved elsewhere (they describe the network, but don't need to be defined repeatedly for each asset-network permutation), and the entire page would no longer be needed, and that would make 1 fewer file that needs to be modified when adding an Axelar asset.

**Comment by jonator** [comment]
How are you thinking we source the erc20 addresses? Via some ethereum endpoint?

**Comment by JeremyParish69** [comment]
> How are you thinking we source the erc20 addresses? Via some ethereum endpoint?

I saw token addresses within some JSONs, but I don't know if they have an API query just for ERC20 addresses--although it might be better to have all this data (it even includes minimum transfer amounts and mint limits):
https://axelar-mainnet.s3.us-east-2.amazonaws.com/mainnet-asset-config.json
